### ISSUE TITLE
Problème d'accès base

### ISSUE THREAD

**Issue by kraoc** [ldleman/Leed-market#109]
Hello,

J'ai l'impression que l'utilisation de ça...

```
$requete = 'SELECT link FROM '.MYSQL_PREFIX.'event WHERE id = '.$event->getId();
$query = mysql_query($requete);
```

...dans les plugins a tendance à faire tomber les mutu...
Bizarrement, j'ai rajouté un plugin qui utilise cette technique et je me suis retrouvé avec un nombre de connections simultanées atteint...

Est-ce qu'on peut se brancher sur le connecteur de Leed d'une manière ou d'une autre ?

**Comment by Simounet** [comment]
Pas de nouvelles depuis longtemps. Je ferme.
