### ISSUE TITLE
Supprimer le plugin themeswitcher ?

### ISSUE THREAD

**Issue by Trim** [ldleman/Leed-market#134]
Hello!

En testant les traductions pour le plugin themeswitcher, je me suis rendu compte qu'il ne modifiait plus comme  il le fallait le paramètre des thèmes (il modifie le fichier constante.php et ne met pas à jour la base de donnée). En plus, maintenant les préférences de Leed  (au moins la version dev) proposent de changer de thème, il n'aurait donc plus lieu d'être dans le Leed-market.

**Comment by Sbgodin** [comment]
fait
