### ISSUE TITLE
[fleedicon_content] site utilisé pour récupérer les icones ne fonctionne plus, correctif proposé

### ISSUE THREAD

**Issue by krypty** [ldleman/Leed-market#140]
Le site utilisé pour récupérer les icones ne fonctionne plus ou à changer d'adresse.

Je propose le correctif suivant dans le fichier: _fleedicon_content.plugin.disabled.php_:

A la ligne 59:
 `$icon = file_get_contents('http://g.etfv.co/' . $url['scheme'] . '://' . $url['host'],0,$ctx);`

A remplacer par: 
`$icon = file_get_contents('http://www.google.com/s2/favicons?domain=' . $url['scheme'] . '://' . $url['host'],0,$ctx);`

Le fait qu'on utilise Google peut aussi éviter que le service ne disparaisse.

Merci d'avance et merci pour Leed :+1: 

PS: le commentaire à la ligne 65 ne serait plus d'actualité également.

**Comment by kvnco** [comment]
Bonjour,

Pour ma part (et pour rester sur le même service), j'avais modifié la requête ainsi :
`$icon = file_get_contents('http://grabicon.com/icon?size=16&domain=' . $url['scheme'] . '://' . $url['host'],0,$ctx);`

Mais le gros Google est aussi une bonne solution. :)

**Comment by krypty** [comment]
Bonjour,

Merci pour cette solution. Elle apporte une alternative interessante également pour les autres et moi-même.

**Comment by kvnco** [comment]
Grabicon vient à nouveau de changer son API en ajoutant un paramètre obligatoire.
Voici la ligne modifiée en conséquence:
`$icon = file_get_contents('http://grabicon.com/icon?origin=abcd.com&size=16&domain=' . $url['scheme'] . '://' . $url['host'],0,$ctx);`

Finalement, c'est pas mal Google, comme solution. ;)

**Comment by kvnco** [comment]
Je viens de faire le pull request #141 sur le sujet :)

**Comment by krypty** [comment]
Haha. Bonne initiative! Merci !

**Comment by Simounet** [comment]
Merci bien kvnco. Juste pour savoir, sur quelle branche de Leed êtes-vous ? J'ai fait la modif' de mon côté pour utiliser Grabicon, le nouveau service qui a remplacé etfv, il faut que je la pousse mais elle va avec des modifs qui ne sont accessibles que sur la branche de dev de Leed...

**Comment by kvnco** [comment]
J'ai fait le patch sur le master… :-/ Tu peux écraser mon pull request si besoin. ;)

**Comment by Simounet** [comment]
C'est pas bien grave, c'était plus à titre d'info pour savoir sur quelle branche vous utilisiez Leed.

**Comment by Simounet** [comment]
J'ai fait pas mal de modifications sur une branche de test. Si ça vous intéresse : https://github.com/Simounet/Leed-market/commits/feature/fleedicon_content-v2 .

**Comment by Simounet** [comment]
Je ferme car une version qui fonctionne est disponible ici : https://github.com/Leed-market/fleedicon_content .
