### ISSUE TITLE
Fatal URL_Clean

### ISSUE THREAD

**Issue by sebastienserre** [ldleman/Leed-market#147]
`Fatal error: Cannot redeclare urlclean_plugin_link() (previously declared in /home/sebastie/public_html/prod/leed/plugins/urlclean-master/urlclean.plugin.disabled.php:18) in /home/sebastie/public_html/prod/leed/plugins/urlclean/urlclean.plugin.disabled.php on line 18`

Becomes after an update!

**Comment by Sbgodin** [comment]
Hello, vu d'ici j'ai l'impression que deux copies du greffon sont chargés : _urlclean-master_ et _urlclean_. Je suppose qu'il faut supprimer l'un des deux.

**Comment by sebastienserre** [comment]
je suis d'acoord, c'est que j'ai d'ailleurs fait mais pourquoi un urlclean-master et un urlclean ?

**Comment by Sbgodin** [comment]
À voir le nom de ces répertoires, je conjecture que _urlclean-master_ vient d'un téléchargement de la branche _master_ sur Github.

Et avec un seul, ça fonctionne ?

**Comment by sebastienserre** [comment]
oui avec un seul pas de soucis
